name: Main Pipeline

on:
  push:
    branches: ["*", "**/*"]
    tags: ["*", "**/*"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NAMESPACE: dsv
  APP_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          file: .ci/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Digital Ocean client
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.TOKEN }}
      - name: Save Digital Ocean kubeconfig
        env:
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        run: doctl kubernetes cluster kubeconfig save $CLUSTER_NAME
      - name: Deploy
        env:
          APP_DOMAIN: ${{env.NAMESPACE}}.${{ secrets.DOMAIN }}
          BRANCH_NAME: ${GITHUB_REF_NAME}
        run: |
          envsubst < .ci/claim.yml > .ci/k8s-4642-claim.yml
          envsubst < .ci/secret.yml > .ci/k8s-4642-secret.yml
          envsubst < .ci/service.yml > .ci/k8s-4642-service.yml
          envsubst < .ci/deployment.yml > .ci/k8s-4642-deployment.yml
          envsubst < .ci/ingress.yml > .ci/k8s-4642-ingress.yml
          kubectl apply -f .ci/k8s-4642-claim.yml
          kubectl apply -f .ci/k8s-4642-secret.yml
          kubectl apply -f .ci/k8s-4642-service.yml
          kubectl apply -f .ci/k8s-4642-deployment.yml
          kubectl apply -f .ci/k8s-4642-ingress.yml
      - name: Verify deployment
        run: kubectl rollout status -n ${NAMESPACE} deployment/${APP_NAME}
